README.markdown

Without the colon you'll get a "undefined local variable or method `id`" error.

Fix typo in export list example usage

---

lib/gibbon/export.rb
spec/gibbon/gibbon_spec.rb

I reported #102 back in November to MC and they said that the Export API was permanently changed to return a single empty space as the response payload if there was nothing to return. #102 fixed that, but starting recently, MC has reverted back to the old behavior of returning a zero length response.
This patch to the patch should accommodate for both scenarios

Eport API: Zero length response gacks with "undefined method `strip' for nil:NilClass"

---

lib/gibbon/export.rb
spec/gibbon/gibbon_spec.rb

Currently setting `Gibbon::Export.timeout` does not work. It instead uses the value set for `Gibbon::API` or the default.
**Current:**
```Ruby
Gibbon::Export.timeout = 45
export = Gibbon::Export.new
export.timeout
=> 30
```
This change fixes it.
**After:**
```Ruby
Gibbon::Export.timeout = 45
export = Gibbon::Export.new
export.timeout
=> 45
```

Fix bug where export timeout doesn't get set

---

Gemfile
README.markdown
gibbon.gemspec
lib/gibbon/api_category.rb
lib/gibbon/export.rb
lib/gibbon/version.rb
spec/gibbon/gibbon_spec.rb

The export wrapper of the Mailchimp API wrapper "Gibbon" loads all the exported data first in memory, before returning it. Since with exporting data, there can be lots and lots of data, this seemed fairly inefficient. This fork solves this.
The changes are as following:
* Instead of httparty, the basic net::http interface is used to stream data directly from the Mailchimp API.
* The export API functions now require a &block to feed each row of data to.
* The export test functions use webmock to fake and verify net::http requests.
* Some re-arrangement of functions (parse_response at APICategory.rb)
All you can do with the normal Gibbon API Wrapper. Plus, parsing each row of exported data while it is being received from the export API:
```
ge = Gibbon::Export.new("your_api_key") …
```

Streaming export API

---

lib/gibbon/api_category.rb

If I got it right this fixes issue with calling the Export methods right on the class without creating an instance, which now throws an error:
```
TypeError: [:campaignSubscriberActivity, {:id=>"ed447bec9e"}] is not a symbol
from /home/dveleba/.rvm/gems/ruby-2.1.6@commstat/gems/gibbon-1.1.6/lib/gibbon/api_category.rb:63:in `send'
from /home/dveleba/.rvm/gems/ruby-2.1.6@commstat/gems/gibbon-1.1.6/lib/gibbon/export.rb:108:in `method_missing'
```

Expand args for __send__ at ApiCategory#send

---

lib/gibbon/export.rb

Simple fix to add a newline when reading from the export API, see issue https://github.com/amro/gibbon/issues/125.

fix newline issue when parsing from export API

---

gibbon.gemspec
lib/gibbon/api_request.rb
lib/gibbon/request.rb
spec/gibbon/upsert_spec.rb

Upsert requests (using PUT method) are useful to update existing or
create a new entity within a single API call.

Support upsert requests

---

lib/gibbon/mailchimp_error.rb
spec/gibbon/api_request_spec.rb

This fixes #154.
It appeared that the intention of [this line](https://github.com/amro/gibbon/blob/439a321bea4abb08c6e9de16f6cbecfa110e69c5/lib/gibbon/api_request.rb#L109) originally via b021d1294593746d9c0aaa70bb5b258292e0e374 to have a `MailChimpError#message` method, as I've added in this PR.
If it'd be better to use one of the existing instance methods on `MailChimpError` class, just lemme know and I'll update this.
Cheers! :beers:

Fix how unparseable Faraday request exception is surfaced

---

lib/gibbon/api_request.rb

If Faraday.new is called with the string url as first parameter,
default_connection_options are respected. This allows i.e. to set ssl
options to Faraday prior to Gibbon actions.
Currently the cert chain of the endpoint I'm using is broken, so all calls fail with SSL errors.
Instead of overwriting OpenSSL constants to set verify to false, with this patch I can temporarily change SSL-Options like
```ruby
Faraday.default_connection_options[:ssl] = Faraday::SSLOptions.new(false)
gibbon.lists.retrieve
Faraday.default_connection_options[:ssl] = nil
```

Allow Farady default_connection_options

---

README.markdown

Hi Amro. Thanks very much for creating gibbon and keeping it up to date with Mailchimp's v3 API. I thought it might be useful to add a few more campaign examples to the readme file, and I hope this will prevent some issues being raised on your github repo :)

Restructure readme file and add examples for campaigns

---

lib/gibbon/api_request.rb
lib/gibbon/mailchimp_error.rb

We don't need to reassign `@message` because it is assigned during error init:
```ruby
error_to_raise = MailChimpError.new(error.message)
```
Fixes #170

Do not override MailChimpError @message, fix #170

---

lib/gibbon/api_request.rb
lib/gibbon/mailchimp_error.rb

This changes the way how `MailChimpError` exception looks for printing in console and e.g. for Sidekiq retries queue.  
Instead of
```ruby
Gibbon::MailChimpError the server responded with status 400
```
It will also print all the valuable instance variables
```ruby
Gibbon::MailChimpError the server responded with status 400 @title="Member Exists", @detail="john@example.com is already a list member. Use PUT to insert or update list members.", @body={"type"=>"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/", "title"=>"Member Exists", "status"=>400, "detail"=>"john@example.com is already a list member. Use PUT to insert or update list members.", "instance"=>""}, @raw_body="{\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\" …
```

Make MailChimpError printing more informative

---

README.markdown

`lower_case_md5_hashed_email_address` is used for all `#members` actions where some kind of id is needed.

Use email hash for all list members actions

---

README.markdown

V3 of the API defaults to 10 responses when you get subscribers. It's easy to miss in the docs and stumped me for hours. These examples should help others.

Updated Read me with additional examples

---

README.markdown

added an example of rescuing a `Gibbon::MailChimpError` in **Error handling**

clarifies error handling syntax

---

lib/gibbon/api_request.rb

API request errors are not returning the body of the response when it is not in JSON format. 
I reordered the lines so that the status code and raw body are captured before attempting to parse the json

capture :status_code and :raw_body

---

README.markdown

Just a basic example of scheduling a campaign added to the (already awesome) readme

Added an example of scheduling a campaign

---

README.markdown

Four of the code examples in the Interests section used inconsistent names for the Gibbon object. Renaming objects `g` to `gibbon` to match the rest of the examples in the document.

Renaming inconsistent Gibbon object names

---

README.markdown
lib/gibbon/api_request.rb
lib/gibbon/request.rb
spec/gibbon/api_request_spec.rb
spec/gibbon/gibbon_spec.rb

If you are used to using symbols as hash keys in your code, you might want to deal with symbols in MailChimp responses too.
This Pull Request adds a `symbolize_keys` option (default to `false`), that will be passed to `MultiJson.load()` function.

Add symbolize_keys option

---

README.markdown

Added spaces between words and markdown syntax to allow proper heading rendering. This makes the Readme document a bit more scannable when viewing on Github.
`##Heading` vs new `## Heading`

Update README.markdown formatting

---

README.markdown

Header was not being parsed as markdown header and displayed as "##Important Notes" on Github.

Missing space to parse as markdown header

---

lib/gibbon/api_request.rb
spec/gibbon/api_request_spec.rb

When `symbolize_keys` is true the `MailChimpError` title and detail fields are always nil because `ApiRequest#handle_error` uses strings to access the parsed error.
This change switches between string and symbol keys based on the value of `symbolize_keys`.

Switch between string and symbol keys for accessing parsed_response

---

lib/gibbon/api_request.rb
spec/gibbon/mailchimp_error_spec.rb

- Bug fix for [issue 253](https://github.com/amro/gibbon/issues/253)
- Adding specs for `Gibbon::MailChimpError`

Adds spec for MailChimpError; fixes error instantiation in APIRequest

---

lib/gibbon/api_request.rb
lib/gibbon/export.rb

Mailchimp is deprecating support for TLS versions 1.0 and 1.1 in their API.
https://devs.mailchimp.com/blog/tls-1-0-and-1-1-deprecation/
This change enforces the use of TLSv1.2.
Fixes #259

Enforce TLSv1.2

---

spec/gibbon/gibbon_spec.rb

minor cosmetic change to a test to fix an inconsistent env variable name.

fix typo MAILCHIMP_PROXY in spec

---

README.markdown

As discussed in #280 this PR slightly changes the wording in the readme to clarify that a single call will not return all available results from the API but rather the first page of results.

Update readme for clarity on retrieve calls

---

lib/gibbon/api_request.rb
spec/gibbon/api_request_spec.rb

I ran into the issue mentioned here - https://github.com/amro/gibbon/issues/283
This adds future compatibility support + preserves backwards compatibility
This is probably easier to review with whitespace diff enabled (https://github.com/amro/gibbon/pull/284/files?w=1)

Add support for Faraday v0.16.0 error class changes.

---

CHANGELOG.md

Seems like you accidentally copied the previous version number in changelog when you probably meant to use v3.3.0 :relaxed:

Fix incorrect version number in changelog

---

lib/gibbon/api_request.rb

Remove reference to error class used by older versions of Faraday

---

Gemfile
gibbon.gemspec
spec/gibbon/api_request_spec.rb
spec/gibbon/upsert_spec.rb

The version of WebMock used has issues with Ruby 2.4+ (although for some
reason this hasn't come up on Travis until now) - c.f.
https://github.com/bblimke/webmock/issues/683
- Bump `webmock` gem to latest version
- Change `stub_request` calls to use new basic auth syntax introduced
with WebMock 2.0

Update WebMock gem to 3.x

---

lib/gibbon/export.rb
spec/gibbon/export_spec.rb

This allows `Gibbon::Export` to read an API key from the
`MAILCHIMP_API_KEY` environment variable if it isn't explicitly
specified, making it consistent with `Gibbon::Request`.

Allow Export API to read API key from environment

---

gibbon.gemspec
lib/gibbon/api_request.rb

```ruby
Faraday.request :basic_auth, "user", "pass"
```
Does not populate request headers with `Authorization: Bearer pass` resulting in 401 Unauthorized response.
Must use instead : 
```ruby
Faraday.basic_auth "user", "pass"
```
Cheers !

Fix basic auth not working with Faraday.request

---

lib/gibbon/api_request.rb

This should continue to work with Faraday 1.x as well (the tests were green when I forced the gemspec to use Faraday 1.9).
Faraday's documentation which covers this change:
https://lostisland.github.io/faraday/middleware/authentication

Support Faraday 2's approach for basic_auth.

---

lib/gibbon/api_request.rb
spec/gibbon/gibbon_spec.rb

Due to the concatenation of domains, it's possible to spoof the information into something unexpected, leading essentially to a Server Side Request Forgery.
Instead of validating the api-key format, which could change and could be escaped by playing cat/mouse game around allowed characters/encoding, I've preferred relying on the Ruby parsing of URL post-creation to ensure that the end result is what we expect.
The error itself is not very self-explanatory, happy to change it if you have a better idea :)
Cheers

Raise if the root domain changed unexepectedly

---

README.markdown

Adds an example of a permanent user delete from a list, as discussed in #300

Add permanent user delete example
